"""Initial Commit fix 

Revision ID: 0c2dddf42a5f
Revises: 4f1c6f3f53aa
Create Date: 2025-08-04 10:43:05.431946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2dddf42a5f'
down_revision: Union[str, None] = '4f1c6f3f53aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
